# demo03_成年人薪资预测

In [1]:
import numpy as np
import pandas as pd

In [18]:
import sklearn.preprocessing as sp
data = pd.read_csv('../data/adult.txt', header=None)
data.head(3)
data[1] = sp.LabelEncoder().fit_transform(data[1])
data[3] = sp.LabelEncoder().fit_transform(data[3])
data[5] = sp.LabelEncoder().fit_transform(data[5])
data[6] = sp.LabelEncoder().fit_transform(data[6])
data[7] = sp.LabelEncoder().fit_transform(data[7])
data[8] = sp.LabelEncoder().fit_transform(data[8])
data[9] = sp.LabelEncoder().fit_transform(data[9])
data[13] = sp.LabelEncoder().fit_transform(data[13])
data[14] = sp.LabelEncoder().fit_transform(data[14])
data

       0   1       2   3   4   5   6   7   8   9      10    11  12  13  14
0      39   7   77516   9  13   4   1   1   4   1   2174     0  40  39   0
1      50   6   83311   9  13   2   4   0   4   1      0     0  13  39   0
2      38   4  215646  11   9   0   6   1   4   1      0     0  40  39   0
3      53   4  234721   1   7   2   6   0   2   1      0     0  40  39   0
4      28   4  338409   9  13   2  10   5   2   0      0     0  40   5   0
5      37   4  284582  12  14   2   4   5   4   0      0     0  40  39   0
6      49   4  160187   6   5   3   8   1   2   0      0     0  16  23   0
7      52   6  209642  11   9   2   4   0   4   1      0     0  45  39   1
8      31   4   45781  12  14   4  10   1   4   0  14084     0  50  39   1
9      42   4  159449   9  13   2   4   0   4   1   5178     0  40  39   1
10     37   4  280464  15  10   2   4   0   2   1      0     0  80  39   1
11     30   7  141297   9  13   2  10   0   1   1      0     0  40  19   1
12     23   4  122272   9  13   4   1   3   4   0      0     0  30  39   0
13     32   4  205019   7  12   4  12   1   2   1      0     0  50  39   0
14     40   4  121772   8  11   2   3   0   1   1      0     0  40   0   1
15     34   4  245487   5   4   2  14   0   0   1      0     0  45  26   0
16     25   6  176756  11   9   4   5   3   4   1      0     0  35  39   0
17     32   4  186824  11   9   4   7   4   4   1      0     0  40  39   0
18     38   4   28887   1   7   2  12   0   4   1      0     0  50  39   0
19     43   6  292175  12  14   0   4   4   4   0      0     0  45  39   1
20     40   4  193524  10  16   2  10   0   4   1      0     0  60  39   1
21     54   4  302146  11   9   5   8   4   2   0      0     0  20  39   0
22     35   1   76845   6   5   2   5   0   2   1      0     0  40  39   0
23     43   4  117037   1   7   2  14   0   4   1      0  2042  40  39   0
24     59   4  109015  11   9   0  13   4   4   0      0     0  40  39   0
25     56   2  216851   9  13   2  13   0   4   1      0     0  40  39   1
26     19   4  168294  11   9   4   3   3   4   1      0     0  40  39   0
27     54   0  180211  15  10   2   0   0   1   1      0     0  60  35   1
28     39   4  367260  11   9   0   4   1   4   1      0     0  80  39   0
29     49   4  193366  11   9   2   3   0   4   1      0     0  40  39   0
...    ..  ..     ...  ..  ..  ..  ..  ..  ..  ..    ...   ...  ..  ..  ..
32531  30   0   33811   9  13   4   0   1   1   0      0     0  99  39   0
32532  34   4  204461  10  16   2  10   0   4   1      0     0  60  39   1
32533  54   4  337992   9  13   2   4   0   1   1      0     0  50  24   1
32534  37   4  179137  15  10   0   1   4   4   0      0     0  39  39   0
32535  22   4  325033   2   8   4  11   3   2   1      0     0  35  39   0
32536  34   4  160216   9  13   4   4   1   4   0      0     0  55  39   1
32537  30   4  345898  11   9   4   3   1   2   1      0     0  46  39   0
32538  38   4  139180   9  13   0  10   4   2   0  15020     0  45  39   1
32539  71   0  287372  10  16   2   0   0   4   1      0     0  10  39   1
32540  45   7  252208  11   9   5   1   3   4   0      0     0  40  39   0
32541  41   0  202822  11   9   5   0   1   2   0      0     0  32  39   0
32542  72   0  129912  11   9   2   0   0   4   1      0     0  25  39   0
32543  45   2  119199   7  12   0  10   4   4   0      0     0  48  39   0
32544  31   4  199655  12  14   0   8   1   3   0      0     0  30  39   0
32545  39   2  111499   7  12   2   1   5   4   0      0     0  20  39   1
32546  37   4  198216   7  12   0  13   1   4   0      0     0  40  39   0
32547  43   4  260761  11   9   2   7   0   4   1      0     0  40  26   0
32548  65   6   99359  14  15   4  10   1   4   1   1086     0  60  39   0
32549  43   7  255835  15  10   0   1   2   4   0      0     0  40  39   0
32550  43   6   27242  15  10   2   3   0   4   1      0     0  50  39   0
32551  32   4   34066   0   6   2   6   0   0   1      0     0  40  39   0
32552  43   4   84661   8  11   2  12   0   4   1      0     0  45  39   0
32553  32   4  116138  12  14   4  13   1   1   1      0     0  11  36   0
32554  53   4  321865  12  14   2   4   0   4   1      0     0  40  39   1
32555  22   4  310152  15  10   4  11   1   4   1      0     0  40  39   0
32556  27   4  257302   7  12   2  13   5   4   0      0     0  38  39   0
32557  40   4  154374  11   9   2   7   0   4   1      0     0  40  39   1
32558  58   4  151910  11   9   6   1   4   4   0      0     0  40  39   0
32559  22   4  201490  11   9   4   1   3   4   1      0     0  20  39   0
32560  52   5  287927  11   9   2   4   5   4   0  15024     0  40  39   1

[32561 rows x 15 columns]

In [14]:
# 年龄、工作类型、序号、学历、工龄、婚姻、工作岗位、家庭身份、
# 人种、性别、投资收益、投资亏损、每周工作小时数、国籍、薪资水平
# data.info()
# data.describe()
# data[14].value_counts()

 <=50K    24720
 >50K      7841
Name: 14, dtype: int64

In [17]:
import sklearn.ensemble as se
import sklearn.model_selection as ms

# 整理输入与输出
x, y = data.loc[:, :13], data[14]
# 创建模型
model = se.RandomForestClassifier(
    max_depth=9, n_estimators=140, random_state=7)
# 交叉验证
s = ms.cross_val_score(model, x, y, cv=5, scoring='f1_weighted')
s.mean()

0.8461273148812696